# Generated by Django 4.2.4 on 2023-10-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulemessages',
            options={'managed': False},
        ),
    ]
