# Generated by Django 4.2.4 on 2023-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('creation_date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
