# Generated by Django 4.2.4 on 2023-10-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='creation_date',
            new_name='date',
        ),
    ]
