# Generated by Django 4.2.4 on 2023-10-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_alter_config_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='config',
            table='configs',
        ),
    ]
